### ISSUE TITLE
double markdown block 

### ISSUE THREAD

**Issue by softquantum** [torchbox/wagtail-markdown#141]
I am following the documentation and started a brand new project.
I added a page class with a body such as:
```
    body = StreamField(
        [
            ("heading", blocks.CharBlock(form_classname="title")),
            ("paragraph", blocks.RichTextBlock()),
            ("image", ImageChooserBlock()),
            ("markdown", MarkdownBlock(icon="code")),
        ]
    )
```

<img width="395" alt="image" src="https://github.com/torchbox/wagtail-markdown/assets/22323588/2a3d18bb-2d0c-459e-b305-9ba2101ebe4a">

<img width="948" alt="image" src="https://github.com/torchbox/wagtail-markdown/assets/22323588/d90e6140-3bc5-41d8-88c3-7ee91ae174b9">

What am I missing ?.  If this is a real bug (and not a code 18), point me in the right direction so I can try to contribute.

Thank you

**Comment by lb-** [comment]
I wonder if the JS is somehow loading twice, first with the initial form payload and then again when the block is added?

This could be a bit of a bug in our documentation, maybe we should indicate what to do if some other code (your own) has already registered the same controller identifier).

I have not run the plugin myself but it would be good to see a console output @softquantum  or probably better, a network log to see if somehow `.../static/wagtailmarkdown/js/easymde-controller.js` is being loaded twice.

Generally, overriding the same controller identifier should not be an issue but if it happens within a very short time, but there is a delay, it will disconnect the current controller and connect it again with the new code.

IF (lots of assumptions) this is the issue, I see two solutions;

1. Add `disconnect` logic to the controller to remove the attached mde editor https://stimulus.hotwired.dev/reference/lifecycle-callbacks#disconnection 
2. Check if the same identifier exists before attaching (a bit clunkcy, so I would not suggest this).
3. Ideally: Find out how to avoid the same JS loading twice.


---

All that being said, another thing to check is if somehow `data-controller="easymde"` is on two elements.

**Comment by lb-** [comment]
OK, ignore above, the issue is that the widget adapter is ALSO instantiating the Markdown editor.

https://github.com/torchbox/wagtail-markdown/blob/15e01cbdd3b20baee9286313ac23347ab32e19df/src/wagtailmarkdown/static/wagtailmarkdown/js/markdown-textarea-adapter.js#L6-L13

Note that you can completely block the URL for the controller code and the editor will still start.

<img width="2051" alt="Screenshot 2024-03-09 at 8 34 54 pm" src="https://github.com/torchbox/wagtail-markdown/assets/1396140/6b5da2ae-b808-44f6-8ec5-80469c8f6e2c">

The whole idea of the Stimulus approach is that you likely will not need as much code in the Telepath widget adapter AND the non-block (Django widget) code.

Both just render an `input` with the same data attributes and in turn will trigger the JS code in your controller. No matter how that input is added (initial DOM in the form or dynamically via Telepath for blocks or InlinePanel or anything else like within a dynamic async modal).

Removing `        easymdeAttach(id);` should be enough, but as you need the same JS to work for 6.0 and not I suggest the following adjustment.

```diff
    MarkdownTextarea.prototype.render = function(placeholder, name, id, initialState) {
        placeholder.outerHTML = this.html.replace(/__NAME__/g, name).replace(/__ID__/g, id);

        var element = document.getElementById(id);
        element.value = initialState;

--        easymdeAttach(id);
++        if (!element.matches('[data-controller~="easymde"') {
++          // Wagtail 6.0, using data attribute (Stimulus), does not require Telepath to instantiate MD Editor
++          easymdeAttach(id);
++        }
```

**Comment by lb-** [comment]
@zerolab - not sure if we need to maybe call out this kind of thing a bit clearer in our documentation.

Would love your thoughts also @katdom13  - thanks for working through these kinds of changes in many packages. We are keen to get your thoughts on how we can make this easier to migrate for others or any feedback.

Feel free to add to the discussion here https://github.com/wagtail/wagtail/discussions/11125

**Comment by zerolab** [comment]
@lb-  I think it is worth calling it out and perhaps providing a migration guide with specific examples

**Comment by softquantum** [comment]
Wow, such a fast response, thank you !

**Comment by zerolab** [comment]
PR up at https://github.com/torchbox/wagtail-markdown/pull/142

**Comment by zerolab** [comment]
https://github.com/torchbox/wagtail-markdown/releases/tag/v0.12.1
